name: Deploy Frontend and Backend to EC2
on:
  push:
    branches: [ main, dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Build and Deploy Frontend
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Build Frontend
      run: |
        cd frontend
        npm run build
        ls -la dist  # Verify that the dist directory contains files (for Vite)

    - name: Deploy Frontend to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.NAIMAT_HACKOPS }}
        source: "frontend/dist/*"  # Use dist folder instead of build
        target: "/home/ec2-user/naimat/frontend"

    # Build and Deploy Backend
    - name: Install Backend Dependencies
      run: |
        cd backend/backend  # Adjust path according to the structure
        npm install

    - name: Deploy Backend to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.NAIMAT_HACKOPS }}
        source: "backend/backend/*"
        target: "/home/ec2-user/naimat/backend"

    # Restart Both Apps with PM2
    - name: Restart Frontend and Backend with PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.NAIMAT_HACKOPS }}
        script: |
          cd /home/ec2-user/naimat/frontend
          pm2 stop frontend || true
          pm2 start "serve -s /home/ec2-user/naimat/frontend/frontend/dist -l 5173" --name "frontend"
          cd /home/ec2-user/naimat/backend/backend  # Adjust path to backend
          pm2 stop backend || true
          pm2 start "npm start" --name "backend"
