name: Deploy Frontend and Backend to EC2
on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # Build and Deploy Frontend
    - name: Set up Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
        ls -la dist
    - name: Deploy Frontend to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.NAIMAT_HACKOPS }}
        source: "frontend/dist/*"
        target: "/home/ec2-user/naimat/frontend"
    # Build and Deploy Backend
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
    - name: Deploy Backend to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.NAIMAT_HACKOPS }}
        source: "backend/*"
        target: "/home/ec2-user/naimat/backend"
    # Create .env File on EC2
    - name: Create .env File on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.NAIMAT_HACKOPS }}
        script: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > /home/ec2-user/naimat/backend/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> /home/ec2-user/naimat/backend/.env
          echo "PORT=6000" >> /home/ec2-user/naimat/backend/.env
    # Restart Both Apps with PM2
    - name: Restart Frontend and Backend with PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.NAIMAT_HACKOPS }}
        script: |
          pm2 delete all || true
          cd /home/ec2-user/naimat/frontend
          pm2 start "serve -s dist -l 5173" --name "frontend"
          cd /home/ec2-user/naimat/backend
          pm2 start "npm start" --name "backend"
